add task solution
mate-academy/react_tabs-js pull request #212
Opened 2023-08-24 18:22 UTC by andrew17752985

https://andrew17752985.github.io/react_tabs-js/

2023-08-25 07:15 UTC, maxim2310 requested changes
Great job overall! Just one tiny thing needs to be fixed before approval)

2023-08-25 07:15 UTC, maxim2310 commented on src/App.jsx
> +    }
you need to to this condition in tabs component

2023-08-25 18:16 UTC, TarasHoliuk requested changes

2023-08-25 18:16 UTC, TarasHoliuk commented on src/App.jsx
> +  };
you should handle this:
![image](https://github.com/mate-academy/react_tabs-js/assets/86923089/3469abed-7b55-42a2-9487-39dbbe52482e)

2023-08-26 07:30 UTC, etojeDenys requested changes
<img width="785" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/70220667/adc4dc91-1fcf-463f-a6af-1f26bcd31c8c">
try to fix the tests or feel free to ask in the chat

2023-08-26 14:40 UTC, volodymyr-soltys97 approved these changes

2023-10-19 10:37 UTC, closed without merging