feat: add task solution
mate-academy/react_tabs-js pull request #219
Opened 2023-08-25 14:19 UTC by FrontKid

[DEMO LINK](https://frontkid.github.io/react_tabs-js/)

2023-08-27 19:35 UTC, AngerDESTROYS approved these changes

2023-08-30 10:27 UTC, alexander-ignatow requested changes
Good 👍 

Only few minor issues are there

2023-08-30 10:27 UTC, alexander-ignatow commented on src/App.jsx
> +  const [selectedTabId, setSelectedTabId] = useState('tab-1');
Don't set this via literal

```suggestion
  const [selectedTabId, setSelectedTabId] = useState(tabs[0]);
```

2023-08-30 10:27 UTC, alexander-ignatow commented on src/components/Tabs/Tabs.jsx
> +        {validTab?.content}
:+1:

2023-08-30 10:27 UTC, alexander-ignatow commented on src/components/Tabs/Tabs.jsx
> +  const validTab = tabs.find(tab => tab.id === selectedTabId) ?? tabs[0];
I would fix naming here - like `selectedTab`, etc

2023-08-31 12:10 UTC, roman-mirzoian requested changes
There is no link to the demo in the PR comment.
![image](https://github.com/mate-academy/react_tabs-js/assets/54860641/36a6a985-571c-49be-b957-1d9444d0c076)
![image](https://github.com/mate-academy/react_tabs-js/assets/54860641/fff5d701-b8db-407b-bcb8-bac78fd8197e)

2023-09-01 16:18 UTC, BudnikOleksii approved these changes
Good work 👍

2023-09-01 16:18 UTC, BudnikOleksii commented on src/components/Tabs/Tabs.jsx
> +import CN from 'classnames';
You don't need to name it in the uppercase

2025-07-29 14:22 UTC, closed without merging