add task solution
mate-academy/react_tabs-js pull request #227
Opened 2023-08-27 17:56 UTC by Koliras

[DEMO LINK](https://Koliras.github.io/react_tabs-js/)

2023-08-28 11:43 UTC, voievodik commented on src/components/Tabs/Tabs.jsx
> +          const currentTab = findTabById(tabs, selectedTabId);
Try moving this variable above and use also for the content value because you are repeating the same function twice

2023-08-28 11:44 UTC, voievodik requested changes
Great job! Just a one comment.

2023-08-29 07:13 UTC, voievodik approved these changes

2023-08-29 11:35 UTC, polosanya approved these changes
Nice!

2023-08-29 11:35 UTC, polosanya commented on src/App.jsx
> +        {`Selected tab is ${findTabById(tabs, selectedTabId).title}`}
It would be great to create a variable for selectedTab before

2023-08-29 11:35 UTC, polosanya commented on src/utils.js
> +export const findTabById = (tabs, selectedId) => tabs
🔥

2024-12-16 14:49 UTC, closed without merging