Develop
mate-academy/react_tabs-js pull request #297
Opened 2023-09-14 18:13 UTC by stunnerboyone

[DEMO LINK](https://stunnerboyone.github.io/react_tabs-js/)

2023-09-14 19:02 UTC, Andriy-Shymkiv requested changes

2023-09-16 13:00 UTC, stunnerboyone commented on src/components/Tabs/Tabs.jsx
> +                    && onTabSelected(tab)}
How I can set tab as param if it was destructured?

2023-09-16 15:02 UTC, stunnerboyone commented on src/components/Tabs/Tabs.jsx
> +                    && onTabSelected(tab)}
How can I add tab as a parameter if it was destructured?

2023-09-16 16:13 UTC, VitaliyBodnar requested changes

2023-09-16 16:13 UTC, VitaliyBodnar commented on src/components/Tabs/Tabs.jsx
> +export const Tabs = ({ tabs, selectedTabId, onTabSelected }) => {
agree, please rename it

2023-09-16 17:31 UTC, stunnerboyone commented on src/components/Tabs/Tabs.jsx
> +export const Tabs = ({ tabs, selectedTabId, onTabSelected }) => {
<img width="1163" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/46221837/a3a09db5-e8f4-4355-a2bf-c09c6a289406">
If I rename tests doesn't pass

2023-09-16 17:32 UTC, stunnerboyone commented on src/components/Tabs/Tabs.jsx
> +export const Tabs = ({ tabs, selectedTabId, onTabSelected }) => {
Pass the `onTabSelected` callback to the `Tabs`, it should be called whenever the user selects another tab.
   (Don't call the callback if the tab was not changed)

2023-09-27 16:16 UTC, Esceype approved these changes
GJ🚀🚀🚀

2023-11-21 19:20 UTC, closed without merging