added tabs selector
mate-academy/react_tabs-js pull request #299
Opened 2023-09-16 06:28 UTC by OPTIMISTIXX

[DEMO LINK](https://OPTIMISTIXX.github.io/react_tabs-js/)

2023-09-16 07:54 UTC, etojeDenys requested changes

2023-09-16 07:54 UTC, etojeDenys commented on src/App.jsx
> +  const [selectedTabContent, setSelectedTabContent] = useState('Some text 1');
we can create only one state and save there whole tab, instead of two

2023-09-16 07:54 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +);
<img width="907" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/70220667/6a96b876-fef3-431d-bedd-6f4bc57ec694">
you should implement this component as written here

2023-09-16 08:05 UTC, etojeDenys requested changes

2023-09-16 08:05 UTC, etojeDenys commented on src/App.jsx
> +};
<img width="873" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/70220667/9f3cbcc7-304a-42ef-bce3-0c44d5bdfff3">
Pass the onTabSelected callback to the Tabs, it should be called whenever the user selects another tab. (Don't call the callback if the tab was not changed)
try to fix the tests

2023-09-16 08:05 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +      ))}
we can just render TabContent with selectedContent without the `map`

2023-09-16 08:05 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +      <>Selected tab is </>
```suggestion
      Selected tab is
```

2023-09-29 12:48 UTC, Viktor-Kost requested changes

2023-09-29 12:48 UTC, Viktor-Kost commented on src/App.jsx
> +      }}
```suggestion
      onTabSelect={(tab) => {
        setSelectedTab(tab);
      }}
```

2023-09-29 12:48 UTC, Viktor-Kost commented on src/components/Tabs/Tabs.jsx
> +export const Tabs = ({ states, tabs, selectedTab }) => (
```suggestion
export const Tabs = ({ onTabSelect, tabs, selectedTab }) => (
```

2023-09-29 12:48 UTC, Viktor-Kost commented on src/components/Tabs/Tabs.jsx
> +              data-cy="Tab"
add a react `key`

2023-09-29 12:48 UTC, Viktor-Kost commented on src/components/Tabs/Tabs.jsx
> +                onClick={() => states(tab)}
move this handler to an own function + add a condition to not set tab if this tab is already selected

2023-10-02 10:02 UTC, VitaliyBodnar requested changes

2023-10-02 10:02 UTC, VitaliyBodnar commented on src/components/Tabs/Tabs.jsx
> +                    }
it is bad practise to make anonymous arrow functions in jsx.
make handler in component and pass reference here

2023-10-02 10:02 UTC, VitaliyBodnar commented on src/components/Tabs/Tabs.jsx
> +                data-cy="Tab"
missed key

2023-10-02 11:49 UTC, anastasiiavorobiova requested changes
Good work! Almost done!

2023-10-02 11:49 UTC, anastasiiavorobiova commented on src/App.jsx
> +      }}
```suggestion
      onTabSelect={setSelectedTab}
```

2023-10-02 11:49 UTC, anastasiiavorobiova commented on src/components/Tabs/Tabs.jsx
> +          key={tabs.id}
```suggestion
```

2023-10-02 11:49 UTC, anastasiiavorobiova commented on src/App.jsx
> +      key={tabs.id}
```suggestion
```

2023-10-02 13:08 UTC, lerastarynets approved these changes
You've got this, keep pushing forward!

2025-08-04 16:12 UTC, closed without merging