Solution
mate-academy/react_tabs-js pull request #305
Opened 2023-09-19 15:13 UTC by YuraMisura

[DEMO LINK](https://YuraMisura.github.io/react_tabs-js/)

2023-09-19 15:29 UTC, Viktor-Kost requested changes

2023-09-19 15:29 UTC, Viktor-Kost commented on src/App.jsx
> +  const [selectedTabId, setSelectedTabId] = useState('tab-1');
it's better to use the whole tab in this state
```suggestion
  const [selectedTab, setSelectedTab] = useState(tabs[0]);
```

2023-09-19 15:29 UTC, Viktor-Kost commented on src/App.jsx
> +      onTabSelected={value => setSelectedTabId(value)}
```suggestion
      onTabSelected={tab => setSelectedTab(tab)}
```

2023-09-20 07:03 UTC, etojeDenys requested changes
your demo link doesn't work, try to re-deploy it

2023-09-20 07:53 UTC, closed without merging