solution was created
mate-academy/react_tabs-js pull request #322
Opened 2023-10-03 05:38 UTC by vlad-ptashnichenko

[DEMO LINK](https://vlad-ptashnichenko.github.io/react_tabs-js/)

2023-10-03 06:44 UTC, etojeDenys requested changes

2023-10-03 06:44 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +        ), '')}
we can just use selectTab instead of reduce

2023-10-04 17:01 UTC, etojeDenys requested changes

2023-10-04 17:01 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +              )}
same here, we can just move this condition into the onClick event

2023-10-04 17:02 UTC, etojeDenys requested changes

2023-10-04 17:02 UTC, etojeDenys commented on src/App.jsx
> +  const [selectedTabTitle, setSelectedTabTitle] = useState(tabs[0].title);
looks like redundant state, we can try to find the title using the `tabs` and `selectedTabId`

2023-10-04 17:16 UTC, Viktor-Kost requested changes

2023-10-04 17:16 UTC, Viktor-Kost commented on src/App.jsx
> +  const [selectedTabTitle, setSelectedTabTitle] = useState(tabs[0].title);
```suggestion
  const [selectedTab, setSelectedTab] = useState(tabs[0]);
```

2023-10-04 17:16 UTC, Viktor-Kost commented on src/App.jsx
> +        {`Selected tab is ${selectedTabTitle}`}
```suggestion
        {`Selected tab is ${selectedTab.title}`}
```

2023-10-04 17:16 UTC, Viktor-Kost commented on src/App.jsx
> +        selectedTabId={selectedTabId}
```suggestion
        selectedTabId={selectedTab.id}
```

2023-10-04 17:16 UTC, Viktor-Kost commented on src/App.jsx
> +        }}
```suggestion
        onTabSelected={setSelectedTab}
```

2023-10-04 17:16 UTC, Viktor-Kost commented on src/components/Tabs/Tabs.jsx
> +                )}
move to handler
```
const handleTabSelect = (tab) => () => {
   if(tab.id === selectedTabId) {
     return
   }
   
   onTabSelected(tab)
}
```
```suggestion
                onClick={handleTabSelect(tab)}
```

2024-04-23 13:09 UTC, closed without merging