add tabs
mate-academy/react_tabs-js pull request #492
Opened 2023-12-13 16:09 UTC by Vlad4567

- [DEMO LINK](https://Vlad4567.github.io/react_tabs-js/)

2023-12-13 16:42 UTC, etojeDenys requested changes
feel free to ask me for some help in the chat

2023-12-13 16:42 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +              className={tab.id === selectedTabId ? 'is-active' : ''}
better to use classnames package for such cases

2023-12-13 16:42 UTC, etojeDenys commented on src/App.jsx
> +        selectedTab={selectedTab}
to pass tests, you need to find the selectedTab in the Tabs component, and remove this prop

2023-12-14 15:56 UTC, sTorba24 approved these changes

2026-08-06 08:05 UTC, closed without merging