add tabs
mate-academy/react_tabs-js pull request #563
Opened 2024-01-11 13:46 UTC by AnoriFrell

[DEMO LINK](https://AnoriFrell.github.io/react_tabs-js/)

2024-01-11 14:10 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-01-11 14:10 UTC, anastasiiavorobiova commented on src/App.jsx
> +        clickedTab={clickedTab}
<img width="846" alt="Screenshot 2024-01-11 at 16 08 54" src="https://github.com/mate-academy/react_tabs-js/assets/135232001/3d5cb5bc-1183-43cc-aa7c-b0ce609149ed">

2024-01-11 14:10 UTC, anastasiiavorobiova commented on src/components/Tabs/Tabs.jsx
> +    if (activeTab !== selectedTab) {
Consider comparing ids here

2024-01-13 09:46 UTC, nazarmatsevych approved these changes
🔥

2025-05-20 09:51 UTC, closed without merging