add solution
mate-academy/react_tabs-js pull request #61
Opened 2023-07-04 18:13 UTC by CasioPayYeah

2023-07-04 21:25 UTC, eleonora-demikh requested changes
Great work! Just a few things to fix

2023-07-04 21:25 UTC, eleonora-demikh commented on src/App.jsx
> +        data-cy="tab-content"
You don't need this line here. This attribute is already used in Tabs component

2023-07-04 21:25 UTC, eleonora-demikh commented on src/components/Tabs/Tabs.jsx
> +                  if (currentTab.id !== tab.id) {
It's better to put `if` in a separate function

2023-07-05 12:05 UTC, And678 approved these changes
This is :fire: , approve :heavy_check_mark:

2026-05-18 14:31 UTC, closed without merging