something wrong
mate-academy/react_tabs-js pull request #745
Opened 2024-03-30 06:56 UTC by VadymBryvka

2024-03-30 07:32 UTC, volodymyr-soltys97 requested changes
Hi, there is no demo link, also you need to add demo link to the PR description
<img width="940" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/64750958/8f3e2648-1513-4471-a465-a4808f0af43c">

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +            >
Don't forget about key attribute

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +              className={`${currentTab === tab.id ? 'is-active' : ''}`}
Use the classnames library for add classes with condition

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +                {tab.title}
Use destruction for `tab`

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +                }}
```suggestion
                onClick={() => setTab(index)}
```

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/App.jsx
> +        }}
```suggestion
        setTab={setTab}
```

2024-03-30 07:32 UTC, volodymyr-soltys97 commented on src/App.jsx
> +    </div> */}
Remove comments

2024-03-31 06:33 UTC, loralevitska approved these changes
Well done)

2024-03-31 06:33 UTC, loralevitska commented on src/components/Tabs/Tabs.jsx
> +          {tabs.map(tab => (
```suggestion
          {tabs.map({ id, title, ..... }=> (
```

![image](https://github.com/mate-academy/react_tabs-js/assets/70009205/bf071b0f-2ab3-4803-ba82-5aadefaa6446)

2024-07-30 02:29 UTC, closed without merging