Added solution
mate-academy/react_tabs-js pull request #887
Opened 2024-05-30 17:19 UTC by Kapidastra

[DEMO LINK](https://kapidastra.github.io/react_tabs-js/)

2024-05-30 17:29 UTC, nazarmatsevych requested changes
Almost done, please fix the comment below

2024-05-30 17:29 UTC, nazarmatsevych commented on src/App.jsx
>        <div className="block" data-cy="TabContent">
Move this block to tabs component
![image](https://github.com/mate-academy/react_tabs-js/assets/80700247/0a6e81bb-426a-45da-982c-80283dbdee8c)

2024-05-31 05:08 UTC, etojeDenys requested changes
it should fix the tests

2024-05-31 05:08 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +              className={tab.id === activeTabId ? 'is-active' : ''}
```suggestion
              className={tab.id === currentTab.id ? 'is-active' : ''}
```

2024-05-31 05:08 UTC, etojeDenys commented on src/components/Tabs/Tabs.jsx
> +                  if (tab.id !== activeTabId) {
```suggestion
                  if (tab.id !== currentTab.id) {
```

2024-05-31 07:13 UTC, volodymyr-soltys97 requested changes
Almost done!
Let's make your code better

2024-05-31 07:13 UTC, volodymyr-soltys97 commented on src/App.jsx
> +        Selected tab is {tabs.find(tab => tab.id === activeTabId).title}
Move this logic from jsx to the helper variable and use it here

2024-05-31 07:13 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +              className={tab.id === currentTab.id ? 'is-active' : ''}
Use the classnames library for add class with condition

2024-05-31 07:13 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +              key={tab.id}
Use destruction for `tab`

2024-05-31 08:47 UTC, volodymyr-soltys97 approved these changes
Well done! 🔥

2024-11-19 12:51 UTC, closed without merging