solution
mate-academy/react_tabs-js pull request #94
Opened 2023-07-08 13:35 UTC by DanyloPasko

[DEMO LINK](https://DanyloPasko.github.io/react_tabs-js/)

2023-07-09 18:02 UTC, anastasiiavorobiova requested changes
Great solution! I added a tiny comment to fix

2023-07-09 18:02 UTC, anastasiiavorobiova commented on src/App.jsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
<img width="627" alt="Screenshot 2023-07-09 at 20 58 07" src="https://github.com/mate-academy/react_tabs-js/assets/135232001/23c4686e-917a-40f4-9528-9afb34fb16a2">

2023-07-10 09:41 UTC, OleziO requested changes

2023-07-10 09:41 UTC, OleziO commented on src/components/Tabs/Tabs.jsx
> +                onClick={() => currentTab.id !== tab.id && onTabSelected(tab)}
Create calback function from this and path it here.

2023-07-10 14:36 UTC, anastasiiavorobiova requested changes
Great work! Keep doing!

2023-07-10 14:36 UTC, anastasiiavorobiova commented on src/App.jsx
> +  const [selectedTabId, setSelectedTab] = useState(tabs[0]);
It's not id here, consider setting ids for selectedTabId as it was in the task requirements

2023-07-11 06:48 UTC, vlad-demchuk approved these changes

2025-06-13 14:30 UTC, closed without merging