first try
mate-academy/react_tabs-js pull request #947
Opened 2024-07-03 08:39 UTC by Fugas252mm

2024-07-03 08:44 UTC, volodymyr-soltys97 requested changes
Hi, there is no demo link, also, you need to add demo link to the PR description 
<img width="954" alt="image" src="https://github.com/mate-academy/react_tabs-js/assets/64750958/b502fa76-93a8-47d7-92ca-a8db13a4aa53">

2024-07-03 08:44 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +              className={tab.id === activeTab.id ? 'is-active' : ''}
Use the classnames library for add classes with condition

2024-07-03 08:44 UTC, volodymyr-soltys97 commented on src/components/Tabs/Tabs.jsx
> +                {tab.title}
Use destructuring for `tab`

2024-07-05 10:49 UTC, Fugas252mm commented
[DEMO LINK](https://fugas252mm.github.io/react_tabs-js/)

2024-07-05 11:23 UTC, GUSILLUS requested changes
GJ!

2024-07-05 11:23 UTC, GUSILLUS commented on src/App.jsx
> +  const activeTab = tabs.find(tab => tab.id === activeTabId) || tabs[0];
Consider removing this variable and changing your state to take not only id, but a full tab

2024-07-05 11:23 UTC, GUSILLUS commented on src/components/Tabs/Tabs.jsx
> +  const activeTab = tabs.find(tab => tab.id === activeTabId) || tabs[0];
If you have done previous comment you can remove this also

2024-07-05 11:23 UTC, GUSILLUS commented on src/components/Tabs/Tabs.jsx
> +        {activeTab.content}
`activeTab.content` => `content`

2024-07-05 11:23 UTC, GUSILLUS commented on src/components/Tabs/Tabs.jsx
> +          {tabs.map(({ id, title }) => (
```suggestion
          {tabs.map(({ id, title, content }) => (
```

2024-07-06 11:07 UTC, closed without merging